services:
  postgres:
    image: postgres:15-alpine
    container_name: clinic_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clinic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: clinic_redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: clinic_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: clinic_backend
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=clinic_db;Username=postgres;Password=password"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMq__Host: "rabbitmq"
      Jwt__Key: "super_secret_key_for_testing_purposes_only_12345"
      Jwt__Issuer: "clinic_pos"
      Jwt__Audience: "clinic_pos_users"
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8081"
    container_name: clinic_frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8081"
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
